name: Deploy website to GitHub Pages

on:
  push:
    branches:
      - main  # deploy whenever you push to main
  workflow_dispatch:  # allow manual deploys

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site files
        run: |
          mkdir public
          cp -r --no-clobber $(find . -maxdepth 1 -not -name public -not -name .) public/
          cp -r pages assets scripts public/ || true

          
      - name: Deploy to yourusername.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public
          external_repository: ahsun-tariq/my-academic-site
          publish_branch: main
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
